package com.flappy.pig;

/* This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int mapType = 2130771968;
        public static final int cameraBearing = 2130771969;
        public static final int cameraTargetLat = 2130771970;
        public static final int cameraTargetLng = 2130771971;
        public static final int cameraTilt = 2130771972;
        public static final int cameraZoom = 2130771973;
        public static final int uiCompass = 2130771974;
        public static final int uiRotateGestures = 2130771975;
        public static final int uiScrollGestures = 2130771976;
        public static final int uiTiltGestures = 2130771977;
        public static final int uiZoomControls = 2130771978;
        public static final int uiZoomGestures = 2130771979;
        public static final int useViewLifecycle = 2130771980;
        public static final int zOrderOnTop = 2130771981;
    }

    public static final class drawable {
        public static final int common_signin_btn_icon_dark = 2130837504;
        public static final int common_signin_btn_icon_disabled_dark = 2130837505;
        public static final int common_signin_btn_icon_disabled_focus_dark = 2130837506;
        public static final int common_signin_btn_icon_disabled_focus_light = 2130837507;
        public static final int common_signin_btn_icon_disabled_light = 2130837508;
        public static final int common_signin_btn_icon_focus_dark = 2130837509;
        public static final int common_signin_btn_icon_focus_light = 2130837510;
        public static final int common_signin_btn_icon_light = 2130837511;
        public static final int common_signin_btn_icon_normal_dark = 2130837512;
        public static final int common_signin_btn_icon_normal_light = 2130837513;
        public static final int common_signin_btn_icon_pressed_dark = 2130837514;
        public static final int common_signin_btn_icon_pressed_light = 2130837515;
        public static final int common_signin_btn_text_dark = 2130837516;
        public static final int common_signin_btn_text_disabled_dark = 2130837517;
        public static final int common_signin_btn_text_disabled_focus_dark = 2130837518;
        public static final int common_signin_btn_text_disabled_focus_light = 2130837519;
        public static final int common_signin_btn_text_disabled_light = 2130837520;
        public static final int common_signin_btn_text_focus_dark = 2130837521;
        public static final int common_signin_btn_text_focus_light = 2130837522;
        public static final int common_signin_btn_text_light = 2130837523;
        public static final int common_signin_btn_text_normal_dark = 2130837524;
        public static final int common_signin_btn_text_normal_light = 2130837525;
        public static final int common_signin_btn_text_pressed_dark = 2130837526;
        public static final int common_signin_btn_text_pressed_light = 2130837527;
        public static final int ic_launcher = 2130837528;
        public static final int ic_plusone_medium_off_client = 2130837529;
        public static final int ic_plusone_small_off_client = 2130837530;
        public static final int ic_plusone_standard_off_client = 2130837531;
        public static final int ic_plusone_tall_off_client = 2130837532;
        public static final int splash = 2130837533;
    }

    public static final class layout {
        public static final int activity_splash = 2130903040;
    }

    public static final class raw {
        public static final int atlas = 2130968576;
    }

    public static final class color {
        public static final int common_signin_btn_dark_text_default = 2131034112;
        public static final int common_signin_btn_dark_text_pressed = 2131034113;
        public static final int common_signin_btn_dark_text_disabled = 2131034114;
        public static final int common_signin_btn_dark_text_focused = 2131034115;
        public static final int common_signin_btn_light_text_default = 2131034116;
        public static final int common_signin_btn_light_text_pressed = 2131034117;
        public static final int common_signin_btn_light_text_disabled = 2131034118;
        public static final int common_signin_btn_light_text_focused = 2131034119;
        public static final int common_signin_btn_default_background = 2131034120;
        public static final int common_action_bar_splitter = 2131034121;
        public static final int common_signin_btn_text_dark = 2131034122;
        public static final int common_signin_btn_text_light = 2131034123;
    }

    public static final class id {
        public static final int none = 2131099648;
        public static final int normal = 2131099649;
        public static final int satellite = 2131099650;
        public static final int terrain = 2131099651;
        public static final int hybrid = 2131099652;
        public static final int imgLogo = 2131099653;
    }

    public static final class string {
        public static final int common_google_play_services_install_title = 2131165184;
        public static final int common_google_play_services_install_text_phone = 2131165185;
        public static final int common_google_play_services_install_text_tablet = 2131165186;
        public static final int common_google_play_services_install_button = 2131165187;
        public static final int common_google_play_services_enable_title = 2131165188;
        public static final int common_google_play_services_enable_text = 2131165189;
        public static final int common_google_play_services_enable_button = 2131165190;
        public static final int common_google_play_services_update_title = 2131165191;
        public static final int common_google_play_services_update_text = 2131165192;
        public static final int common_google_play_services_network_error_title = 2131165193;
        public static final int common_google_play_services_network_error_text = 2131165194;
        public static final int common_google_play_services_invalid_account_title = 2131165195;
        public static final int common_google_play_services_invalid_account_text = 2131165196;
        public static final int common_google_play_services_unknown_issue = 2131165197;
        public static final int common_google_play_services_unsupported_title = 2131165198;
        public static final int common_google_play_services_unsupported_text = 2131165199;
        public static final int common_google_play_services_update_button = 2131165200;
        public static final int common_signin_button_text = 2131165201;
        public static final int common_signin_button_text_long = 2131165202;
        public static final int auth_client_using_bad_version_title = 2131165203;
        public static final int auth_client_needs_enabling_title = 2131165204;
        public static final int auth_client_needs_installation_title = 2131165205;
        public static final int auth_client_needs_update_title = 2131165206;
        public static final int auth_client_play_services_err_notification_msg = 2131165207;
        public static final int auth_client_requested_by_msg = 2131165208;
        public static final int gamehelper_sign_in_failed = 2131165209;
        public static final int gamehelper_app_misconfigured = 2131165210;
        public static final int gamehelper_license_failed = 2131165211;
        public static final int gamehelper_unknown_error = 2131165212;
        public static final int app_id = 2131165213;
        public static final int app_name = 2131165214;
    }

    public static final class style {
        public static final int AppTheme = 2131230720;
    }
}
